# The name of the linking book
linking-book-name: "Linking Book"

# Message for using the book in the same dimension
same-dimension-message: "You cannot use this book in the same dimension it was created."

# Custom Model Data for the Linking Book.
# Use this if you want to apply a custom model to the Linking Book.
# Set to 0 to disable custom model data.
linking-book-custom-model-data: 0